const js = require('@eslint/js');

module.exports = [
  js.configs.recommended,
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        // Node.js globals
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        global: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        AbortController: 'readonly',
        fetch: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        structuredClone: 'readonly',
        // Electron globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        HTMLElement: 'readonly',
        customElements: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        getComputedStyle: 'readonly',
        Audio: 'readonly',
        Image: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        EventSource: 'readonly',
        AudioContext: 'readonly',
        MediaRecorder: 'readonly',
        MediaStream: 'readonly',
        RTCPeerConnection: 'readonly',
        performance: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        self: 'readonly',
        // Test globals
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      'no-empty': ['warn', { allowEmptyCatch: false }],
      'no-unused-vars': [
        'warn',
        {
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      'no-promise-executor-return': 'warn',

      'no-undef': 'off',
      'no-redeclare': 'off',
      'no-prototype-builtins': 'off',
      'no-useless-escape': 'off',
      'no-control-regex': 'off',
      'no-constant-condition': 'off',
      'no-async-promise-executor': 'off',
      'no-case-declarations': 'off',
      'no-fallthrough': 'off',
      'no-inner-declarations': 'off',
      'no-irregular-whitespace': 'off',
      'getter-return': 'off',
      'no-misleading-character-class': 'off',
      'no-self-assign': 'off',
      'no-unsafe-finally': 'off',
      'no-unused-labels': 'off',
      'no-extra-boolean-cast': 'off',
      'require-yield': 'off',
      'no-sparse-arrays': 'off',
      'no-useless-catch': 'off',
      'no-dupe-keys': 'off',
    },
  },
  // ES module override for src/, test/, and .mjs files
  {
    files: [
      '**/*.mjs',
      'src/**/*.js',
      'test/**/*.js',
      'agentic-player/**/*.js',
      'lib/icon-library.js',
      'video-editor-modules-bridge.js',
    ],
    languageOptions: {
      sourceType: 'module',
    },
  },
  // Global ignores
  {
    ignores: [
      'node_modules/**',
      '_legacy/**',
      'dist/**',
      'build/**',
      'test/fixtures/**',
      'example-module/**',
      'voice-sdk-package/**',
      'packages/task-exchange/**',
      'packages/task-agent/dist/**',
      'Flipboard-IDW-Feed/**',
      'test/example-automated-tests.js',
    ],
  },
];
