/**
 * Tests for the AI Run Times cached-tts IPC handler logic.
 *
 * The handler lives in `lite/ai-run-times/main.ts` (registered via
 * `initAiRunTimes`). We don't drive Electron IPC here -- that surface
 * is exercised in `event-coverage.test.ts`. Instead we verify the
 * decision tree the handler implements:
 *
 *   1. Cache hit -> return cached bytes, never call AI
 *   2. Cache miss -> call AI, write to cache, return generated bytes
 *   3. Signed-out (Files refuses) -> still call AI, skip cache write
 *   4. Cache lookup HTTP error -> still call AI (don't block on cache)
 *
 * Per ADR-045 the cache key is deterministic
 * (`articleId + voice + sha1(text)`) so re-listening to the same
 * article + voice + chunk hits the cache.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { _setAiApiForTesting, _resetAiApiForTesting, type AiApi } from '../../ai/api.js';
import { _setFilesApiForTesting, _resetFilesApiForTesting, FilesError, FILES_ERROR_CODES, type FilesApi } from '../../files/api.js';

// ─── Test doubles ─────────────────────────────────────────────────────────

interface FakeAiOptions {
  bytes?: Uint8Array;
  throwOnTts?: Error;
}

function makeFakeAi(opts: FakeAiOptions = {}): AiApi & { ttsCalls: Array<{ text: string; voice: string }> } {
  const ttsCalls: Array<{ text: string; voice: string }> = [];
  const fake = {
    ttsCalls,
    tts: async (req: { text: string; voice?: string }) => {
      ttsCalls.push({ text: req.text, voice: req.voice ?? 'nova' });
      if (opts.throwOnTts !== undefined) throw opts.throwOnTts;
      return {
        audio: opts.bytes ?? new Uint8Array([0x49, 0x44, 0x33]), // "ID3" mp3 header bytes
        mimeType: 'audio/mpeg',
        voice: req.voice ?? 'nova',
        model: 'tts-1',
        format: 'mp3' as const,
      };
    },
    chat: async () => {
      throw new Error('not used in these tests');
    },
    status: async () => ({
      provider: 'openai' as const,
      hasApiKey: true,
      defaultTtsVoice: 'nova',
      defaultTtsModel: 'tts-1',
      defaultChatModel: 'gpt-4o-mini',
    }),
    configure: async () => ({ ok: true as const }),
    onEvent: () => () => undefined,
  };
  return fake as unknown as AiApi & { ttsCalls: typeof ttsCalls };
}

interface FakeFilesOptions {
  /** Pre-populate the cache: keyed by full Files key. */
  preCached?: Map<string, Uint8Array>;
  /** Throw this from `download()` instead of returning bytes. */
  throwOnDownload?: Error;
  /** Throw this from `upload()`. */
  throwOnUpload?: Error;
}

function makeFakeFiles(opts: FakeFilesOptions = {}): FilesApi & {
  uploads: Array<{ prefix: string; fileName: string; bytes: number }>;
  downloads: string[];
} {
  const uploads: Array<{ prefix: string; fileName: string; bytes: number }> = [];
  const downloads: string[] = [];
  const cache = opts.preCached ?? new Map<string, Uint8Array>();

  const fake = {
    uploads,
    downloads,
    upload: async (
      prefix: string,
      fileName: string,
      content: ArrayBuffer | Uint8Array,
      _options?: unknown
    ) => {
      uploads.push({
        prefix,
        fileName,
        bytes: content instanceof Uint8Array ? content.length : content.byteLength,
      });
      if (opts.throwOnUpload !== undefined) throw opts.throwOnUpload;
      return `https://files.test/${prefix}/${fileName}`;
    },
    download: async (key: string) => {
      downloads.push(key);
      if (opts.throwOnDownload !== undefined) throw opts.throwOnDownload;
      const hit = cache.get(key);
      if (hit === undefined) {
        throw new FilesError({
          code: FILES_ERROR_CODES.NOT_FOUND,
          message: 'fake-files: not in cache',
          context: { op: 'download', key },
        });
      }
      return hit.buffer.slice(hit.byteOffset, hit.byteOffset + hit.byteLength);
    },
    getDownloadUrl: async (key: string) => `https://files.test/dl/${key}`,
    get: async () => null,
    list: async () => [],
    createFolder: async () => undefined,
    delete: async () => undefined,
    deleteFolder: async () => undefined,
    setTtl: async () => undefined,
    setPrivacy: async () => undefined,
    onEvent: () => () => undefined,
  };
  return fake as unknown as FilesApi & { uploads: typeof uploads; downloads: typeof downloads };
}

/**
 * Re-implements the handler's decision tree as a pure function so we
 * can test it without booting Electron IPC. Mirrors the logic in
 * `lite/ai-run-times/main.ts` (the CACHED_TTS handler body).
 *
 * If this function diverges from the real handler, an integration
 * test against the live IPC catches it -- but for the decision-tree
 * unit shape, this mirror keeps tests focused.
 */
async function cachedTtsThroughHandler(
  input: { articleId: string; text: string; voice: string },
  ai: AiApi,
  files: FilesApi
): Promise<{ audioBase64: string; contentType: string; cached: boolean }> {
  const { createHash } = await import('node:crypto');
  const safeArticleId = input.articleId.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 80);
  const hash = createHash('sha1').update(input.text).digest('hex').slice(0, 12);
  const fileName = `${input.voice}-${hash}.mp3`;
  const prefix = `ai-run-times/tts/${safeArticleId}`;
  const cacheKey = `${prefix}/${fileName}`;

  try {
    const buf = await files.download(cacheKey);
    return {
      audioBase64: Buffer.from(buf).toString('base64'),
      contentType: 'audio/mpeg',
      cached: true,
    };
  } catch (err) {
    if (err instanceof FilesError && err.code === FILES_ERROR_CODES.NOT_AUTHENTICATED) {
      // Signed-out: skip cache, but still generate.
    } else if (err instanceof FilesError && err.code === FILES_ERROR_CODES.NOT_FOUND) {
      // Expected miss path.
    } else {
      // Other failures: still generate, log warn (skipped here).
    }
  }

  const ttsResp = await ai.tts({
    text: input.text,
    voice: input.voice as 'nova',
    format: 'mp3',
    feature: 'ai-run-times',
  });

  // Best-effort cache write (errors swallowed in real handler).
  try {
    await files.upload(prefix, fileName, ttsResp.audio, {
      contentType: 'audio/mpeg',
      isPublic: false,
      rewriteMode: 'rewrite',
      expiresAt: new Date(Date.now() + 30 * 86400_000).toISOString(),
    });
  } catch {
    /* swallow -- cache write failure must not block returning bytes */
  }

  return {
    audioBase64: Buffer.from(ttsResp.audio).toString('base64'),
    contentType: 'audio/mpeg',
    cached: false,
  };
}

// ─── Tests ────────────────────────────────────────────────────────────────

beforeEach(() => {
  _resetAiApiForTesting();
  _resetFilesApiForTesting();
});

describe('cached-tts handler decision tree', () => {
  it('cache hit: returns cached bytes, never calls AI', async () => {
    const cached = new Uint8Array([1, 2, 3, 4]);
    const ai = makeFakeAi();
    // The cache key is sha1 of the text; reproduce it here.
    const { createHash } = await import('node:crypto');
    const hash = createHash('sha1').update('hello world').digest('hex').slice(0, 12);
    const key = `ai-run-times/tts/article-1/nova-${hash}.mp3`;
    const files = makeFakeFiles({ preCached: new Map([[key, cached]]) });
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    const result = await cachedTtsThroughHandler(
      { articleId: 'article-1', text: 'hello world', voice: 'nova' },
      ai,
      files
    );
    expect(result.cached).toBe(true);
    expect(Buffer.from(result.audioBase64, 'base64')).toEqual(Buffer.from(cached));
    expect(ai.ttsCalls).toHaveLength(0);
    expect(files.uploads).toHaveLength(0);
  });

  it('cache miss: calls AI, uploads result, returns generated bytes', async () => {
    const generated = new Uint8Array([7, 8, 9]);
    const ai = makeFakeAi({ bytes: generated });
    const files = makeFakeFiles();
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    const result = await cachedTtsThroughHandler(
      { articleId: 'article-2', text: 'fresh chunk', voice: 'nova' },
      ai,
      files
    );
    expect(result.cached).toBe(false);
    expect(Buffer.from(result.audioBase64, 'base64')).toEqual(Buffer.from(generated));
    expect(ai.ttsCalls).toHaveLength(1);
    expect(files.uploads).toHaveLength(1);
    expect(files.uploads[0]?.prefix).toBe('ai-run-times/tts/article-2');
    expect(files.uploads[0]?.fileName).toMatch(/^nova-[0-9a-f]{12}\.mp3$/);
  });

  it('signed-out: skips cache, calls AI, no upload write', async () => {
    const ai = makeFakeAi({ bytes: new Uint8Array([0xff]) });
    const files = makeFakeFiles({
      throwOnDownload: new FilesError({
        code: FILES_ERROR_CODES.NOT_AUTHENTICATED,
        message: 'no token',
        context: {},
      }),
      throwOnUpload: new FilesError({
        code: FILES_ERROR_CODES.NOT_AUTHENTICATED,
        message: 'no token',
        context: {},
      }),
    });
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    const result = await cachedTtsThroughHandler(
      { articleId: 'article-3', text: 'signed out chunk', voice: 'nova' },
      ai,
      files
    );
    expect(result.cached).toBe(false);
    expect(ai.ttsCalls).toHaveLength(1);
    // Upload was attempted (we don't know up-front the user is signed out)
    // but failure was swallowed.
    expect(files.uploads).toHaveLength(1);
  });

  it('AI failure propagates to caller', async () => {
    const ai = makeFakeAi({ throwOnTts: new Error('OpenAI quota exceeded') });
    const files = makeFakeFiles();
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    await expect(
      cachedTtsThroughHandler(
        { articleId: 'article-4', text: 't', voice: 'nova' },
        ai,
        files
      )
    ).rejects.toThrow(/OpenAI quota exceeded/);
    expect(files.uploads).toHaveLength(0);
  });

  it('cache write failure does NOT block returning bytes', async () => {
    const ai = makeFakeAi({ bytes: new Uint8Array([1]) });
    const files = makeFakeFiles({
      throwOnUpload: new Error('upload server down'),
    });
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    const result = await cachedTtsThroughHandler(
      { articleId: 'article-5', text: 't', voice: 'nova' },
      ai,
      files
    );
    expect(result.cached).toBe(false);
    expect(result.audioBase64).toBe(Buffer.from([1]).toString('base64'));
  });

  it('different voices produce different cache keys (no cross-voice replay)', async () => {
    const aliceBytes = new Uint8Array([0xa1]);
    const echoBytes = new Uint8Array([0xe2]);
    const { createHash } = await import('node:crypto');
    const hash = createHash('sha1').update('same text').digest('hex').slice(0, 12);
    const cache = new Map<string, Uint8Array>([
      [`ai-run-times/tts/article-6/alloy-${hash}.mp3`, aliceBytes],
      [`ai-run-times/tts/article-6/echo-${hash}.mp3`, echoBytes],
    ]);
    const ai = makeFakeAi();
    const files = makeFakeFiles({ preCached: cache });
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    const r1 = await cachedTtsThroughHandler(
      { articleId: 'article-6', text: 'same text', voice: 'alloy' },
      ai,
      files
    );
    const r2 = await cachedTtsThroughHandler(
      { articleId: 'article-6', text: 'same text', voice: 'echo' },
      ai,
      files
    );
    expect(r1.cached).toBe(true);
    expect(r2.cached).toBe(true);
    expect(r1.audioBase64).not.toBe(r2.audioBase64);
    expect(ai.ttsCalls).toHaveLength(0);
  });

  it('articleId with unsafe path chars is sanitized into the prefix', async () => {
    const ai = makeFakeAi({ bytes: new Uint8Array([1]) });
    const files = makeFakeFiles();
    _setAiApiForTesting(ai);
    _setFilesApiForTesting(files);

    await cachedTtsThroughHandler(
      { articleId: 'http://example.com/post?id=42', text: 't', voice: 'nova' },
      ai,
      files
    );
    expect(files.uploads).toHaveLength(1);
    const prefix = files.uploads[0]?.prefix ?? '';
    // Prefix is `ai-run-times/tts/<safeArticleId>` -- the literal
    // segments contribute exactly 2 slashes, so the sanitized id
    // segment must not introduce any more.
    expect(prefix.split('/').length).toBe(3);
    // The sanitized id portion must NOT contain unsafe URL chars.
    const safeIdPortion = prefix.split('/').slice(2).join('/');
    expect(safeIdPortion).not.toContain(':');
    expect(safeIdPortion).not.toContain('?');
    expect(safeIdPortion).not.toContain('=');
    // sha-friendly chars only (the regex in main.ts keeps a-zA-Z0-9._-).
    expect(safeIdPortion).toMatch(/^[a-zA-Z0-9._-]+$/);
  });
});
