/**
 * Test Fixtures
 * Part of the Governed Self-Improving Agent Runtime Testing Infrastructure
 * 
 * Factory functions for test data
 */

import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

export * from './spaces.js';
export * from './aider-responses.js';
export * from './plans.js';
export * from './errors.js';

// Re-export defaults for convenience
import spaces from './spaces.js';
import aiderResponses from './aider-responses.js';
import plans from './plans.js';
import errors from './errors.js';

// ── Media fixture paths ──────────────────────────────────────────────────────
// Generated by: node test/fixtures/media/generate-media-fixtures.js
// These files must exist before running upload/asset-editing tests.

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const mediaDir = join(__dirname, 'media');

/**
 * Absolute paths to media test fixtures.
 * Phase 1 (always available): png, gif, bmp, svg, wav, pdf, txt
 * Phase 2 (requires FFmpeg):  jpg, mp4, mp3, webp
 */
export const MEDIA_FIXTURES = {
  // Images
  png:  join(mediaDir, 'sample.png'),
  jpg:  join(mediaDir, 'sample.jpg'),
  gif:  join(mediaDir, 'sample.gif'),
  bmp:  join(mediaDir, 'sample.bmp'),
  svg:  join(mediaDir, 'sample.svg'),
  webp: join(mediaDir, 'sample.webp'),
  // Video
  mp4:  join(mediaDir, 'sample.mp4'),
  // Audio
  wav:  join(mediaDir, 'sample.wav'),
  mp3:  join(mediaDir, 'sample.mp3'),
  // Documents
  pdf:  join(mediaDir, 'sample.pdf'),
  txt:  join(mediaDir, 'sample.txt'),
};

/**
 * Paths to conversion test fixtures (text-based).
 */
const conversionDir = join(__dirname, 'conversion');

export const CONVERSION_FIXTURES = {
  md:       join(conversionDir, 'sample.md'),
  html:     join(conversionDir, 'sample.html'),
  csv:      join(conversionDir, 'sample.csv'),
  json:     join(conversionDir, 'sample.json'),
  yaml:     join(conversionDir, 'sample.yaml'),
  python:   join(conversionDir, 'sample-code.py'),
  notebook: join(conversionDir, 'sample.ipynb'),
  playbook: join(conversionDir, 'sample-playbook.json'),
};

export default {
  ...spaces,
  ...aiderResponses,
  ...plans,
  ...errors,
  MEDIA_FIXTURES,
  CONVERSION_FIXTURES,
};
